// Cambridge YLE Movers word list (for exams from 2018), extracted from https://www.yle.tw/download/wordlist/Movers.pdf
export const YLE_MOVERS = [
  "above", "address", "afraid", "after", "age", "all", "all right", "along",
  "always", "another", "any", "app", "around", "asleep", "at", "aunt",
  "awake", "back", "bad", "badly", "balcony", "band", "basement", "bat",
  "be called", "beard", "because", "before", "below", "best", "better", "blanket",
  "blond", "boring", "both", "bottle", "bottom", "bowl", "brave", "break",
  "brilliant", "bring", "build", "building", "bus station", "bus stop", "busy", "buy",
  "by", "cage", "call", "car park", "careful", "carefully", "carry", "catch",
  "CD", "center", "centre", "change", "Charlie", "cheese", "cinema", "circle",
  "circus", "city", "city centre", "town centre", "Clare", "clever", "climb", "cloud",
  "cloudy", "clown", "coat", "coffee", "cold", "come on", "comic", "comic book",
  "cook", "cough", "could", "country", "countryside", "cry", "cup", "curly",
  "Daisy", "dance", "dangerous", "daughter", "dentist", "difference", "different", "difficult",
  "doctor", "dolphin", "down", "downstairs", "dream", "dress up", "drive", "driver",
  "drop", "dry", "DVD", "earache", "easy", "e-book", "lift", "elevator",
  "email", "every", "everyone", "everything", "exciting", "excuse me", "fair", "fall",
  "famous", "farm", "farmer", "fat", "feed", "field", "movie", "film",
  "film star", "fine", "first", "fish", "fix", "floor", "fly", "forest",
  "Fred", "Friday", "frightened", "funfair", "get dressed", "get off", "get on", "get undressed",
  "get up", "glass", "go shopping", "goal", "granddaughter", "grandparent", "grandson", "grass",
  "ground", "grow", "grown-up", "have to", "headache", "helmet", "help", "hide",
  "holiday", "homework", "hop", "hospital", "hot", "how", "how much", "how often",
  "huge", "hundred", "hungry", "hurt", "ice", "ice skates", "ice skating", "idea",
  "ill", "inside", "internet", "into", "invite", "island", "Jack", "Jane",
  "Jim", "Julia", "jungle", "kangaroo", "kick", "kind", "kitten", "lake",
  "laptop", "last", "laugh", "leaf", "leaves", "library", "Lily", "lion",
  "little", "look for", "lose", "loud", "loudly", "machine", "map", "market",
  "Mary", "matter", "mean", "message", "milkshake", "mistake", "model", "Monday",
  "moon", "more", "most", "mountain", "moustache", "move", "must", "naughty",
  "near", "neck", "need", "net", "never", "noise", "noodles", "nothing",
  "nurse", "o'clock", "off", "often", "on", "only", "opposite", "out",
  "out of", "outside", "pair", "pancake", "panda", "parent", "parrot", "party",
  "pasta", "Paul", "penguin", "Peter", "picnic", "pirate", "plant", "plate",
  "player", "pool", "pop star", "practice", "practise", "present", "pretty", "puppy",
  "put on", "quick", "quickly", "quiet", "quietly", "rabbit", "rain", "rainbow",
  "ride", "river", "road", "rock", "roller skates", "roller skating", "roof", "round",
  "safe", "sail", "salad", "Sally", "sandwich", "Saturday", "sauce", "scarf",
  "score", "seat", "second", "send", "shall", "shape", "shark", "shop",
  "shopping", "shopping centre", "shoulder", "shout", "shower", "sick", "skate", "skip",
  "sky", "slow", "slowly", "snail", "snow", "someone", "something", "sometimes",
  "son", "soup", "sports centre", "square", "stair", "star", "station", "stomach",
  "stomach-ache", "straight", "strong", "Sunday", "sunny", "supermarket", "surprised", "sweater",
  "sweet", "swim", "swimming pool", "swimsuit", "take", "take off", "tall", "tea",
  "teach", "temperature", "terrible", "text", "than", "then", "thin", "think",
  "third", "thirsty", "Thursday", "ticket", "tired", "tooth", "teeth", "toothache",
  "toothbrush", "toothpaste", "top", "towel", "town", "tractor", "travel", "treasure",
  "trip", "Tuesday", "uncle", "up", "upstairs", "vegetable", "Vicky", "video",
  "village", "wait", "wake", "walk", "wash", "water", "waterfall", "wave",
  "weak", "weather", "website", "Wednesday", "week", "weekend", "well", "wet",
  "whale", "when", "where", "which", "who", "why", "wind", "windy",
  "work", "world", "worse", "worst", "would", "wrong", "yesterday", "Zoe",
];
