// Cambridge YLE Starters word list (for exams from 2018), extracted from https://www.yle.tw/download/wordlist/Starters.pdf
export const YLE_STARTERS = [
  "a", "about", "add", "afternoon", "again", "Alex", "Alice", "alien",
  "alphabet", "an", "and", "angry", "animal", "Ann", "Anna", "answer",
  "flat", "apartment", "apple", "arm", "armchair", "ask", "baby", "badminton",
  "bag", "ball", "balloon", "banana", "baseball", "baseball cap", "basketball", "bat",
  "bath", "bathroom", "be", "beach", "bean", "bear", "beautiful", "bed",
  "bedroom", "bee", "behind", "Ben", "between", "big", "bike", "Bill",
  "bird", "birthday", "black", "blue", "board", "board game", "boat", "body",
  "book", "bookcase", "bookshop", "boots", "bounce", "box", "boy", "bread",
  "breakfast", "brother", "brown", "burger", "bus", "but", "bye", "cake",
  "camera", "can", "sweet", "candy", "car", "carrot", "cat", "catch",
  "chair", "chicken", "at", "child", "children", "fries", "chips", "chocolate",
  "choose", "clap", "class", "classmate", "classroom", "clean", "clock", "close",
  "closed", "clothes", "coconut", "color", "colour", "come", "complete", "computer",
  "cool", "correct", "count", "cousin", "cow", "crayon", "crocodile", "cross",
  "cupboard", "dad", "Dan", "day", "desk", "dining room", "dinner", "dirty",
  "do", "dog", "doll", "donkey", "don't worry", "door", "double", "draw",
  "drawing", "dress", "drink", "drive", "duck", "ear", "eat", "egg",
  "elephant", "end", "English", "enjoy", "rubber", "eraser", "Eva", "evening",
  "example", "eye", "face", "family", "fantastic", "father", "favorite", "favourite",
  "find", "fish", "fishing", "floor", "flower", "fly", "food", "foot",
  "feet", "soccer", "football", "for", "friend", "frog", "from", "fruit",
  "fun", "funny", "game", "garden", "get", "giraffe", "girl", "give",
  "glasses", "go", "go to bed", "go to sleep", "goat", "good", "goodbye", "Grace",
  "grandfather", "grandma", "grandmother", "grandpa", "grape", "grey", "gray", "great",
  "green", "guitar", "hair", "hall", "hand", "handbag", "happy", "hat",
  "have", "have got", "he", "head", "helicopter", "hello", "her", "here",
  "hers", "hi", "him", "hippo", "his", "hit", "hobby", "hockey",
  "hold", "home", "hooray", "horse", "house", "how", "how many", "how old",
  "Hugo", "I", "ice cream", "in", "in front of", "it", "its", "jacket",
  "jeans", "jellyfish", "Jill", "juice", "jump", "keyboard", "kick", "kid",
  "Kim", "kitchen", "kite", "kiwi", "know", "lamp", "learn", "leg",
  "lemon", "lemonade", "lesson", "let's", "letter", "like", "lime", "line",
  "listen", "live", "living room", "lizard", "long", "look", "look at", "truck",
  "lorry", "a lot", "a lot of", "lots", "lots of", "love", "Lucy", "lunch",
  "make", "man", "men", "mango", "many", "Mark", "mat", "Matt",
  "May", "me", "me too", "meat", "meatballs", "milk", "mine", "mirror",
  "Miss", "monkey", "monster", "morning", "mother", "motorbike", "mouse", "mice",
  "mouth", "Mr", "Mrs", "mum", "music", "my", "name", "new",
  "next to", "nice", "Nick", "night", "no", "nose", "not", "now",
  "number", "oh", "oh dear", "OK", "old", "on", "one", "onion",
  "open", "or", "orange", "our", "ours", "page", "paint", "painting",
  "paper", "pardon", "park", "part", "Pat", "pea", "pear", "pen",
  "pencil", "person", "people", "pet", "phone", "photo", "piano", "pick up",
  "picture", "pie", "pineapple", "pink", "plane", "play", "playground", "please",
  "point", "polar bear", "poster", "potato", "purple", "put", "radio", "read",
  "really", "red", "rice", "ride", "right", "robot", "room", "rug",
  "ruler", "run", "sad", "Sam", "sand", "sausage", "say", "scary",
  "school", "sea", "see", "see you", "sentence", "she", "sheep", "shell",
  "ship", "shirt", "shoe", "store", "shop", "short", "shorts", "show",
  "silly", "sing", "sister", "sit", "skateboard", "skateboarding", "skirt", "sleep",
  "small", "smile", "snake", "so", "sock", "sofa", "some", "song",
  "sorry", "spell", "spider", "sport", "stand", "start", "stop", "story",
  "street", "Sue", "sun", "swim", "question", "table", "table tennis", "tablet",
  "tail", "take a photo", "take a picture", "talk", "teacher", "teddy", "television", "TV",
  "tell", "tennis", "tennis racket", "thank you", "thanks", "that", "the", "their",
  "theirs", "them", "then", "there", "these", "they", "thing", "this",
  "those", "throw", "tick", "tiger", "to", "today", "Tom", "tomato",
  "too", "toy", "train", "tree", "trousers", "try", "T-shirt", "ugly",
  "under", "understand", "us", "wave", "we", "wear", "well", "well done",
  "what", "where", "which", "white", "who", "whose", "window", "with",
  "woman", "women", "word", "would like", "wow", "write", "young", "your",
  "yours", "very", "walk", "wall", "want", "watch", "water", "watermelon",
  "year", "yellow", "yes", "you", "zebra", "zoo",
];
